name: cinemapedia
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^3.0.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.6.2
  go_router: ^9.0.3
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  riverpod_annotation: ^2.1.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.3
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon-4.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#ffffff"
  # image: assets/icon/app-icon-4.png
  color_dark: "#252829"
  # image_dark: assets/icon/app-icon-4.png

  android_12:
    # image: assets/icon/app-icon-4.png
    icon_background_color: "#ffffff"
    # image_dark: assets/icon/app-icon-4.png
    icon_background_color_dark: "#252829"
  android: true
  ios: true
    
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/icon/
